version: "3.9"

services:
  app:
    build: .
    image: cv-webapp-app:latest
    container_name: cv-webapp-app
    environment:
      APP_ENV: "prod"
    expose:
      - "8000"
    restart: unless-stopped

  caddy:
    image: caddy:2.8-alpine
    container_name: cv-webapp-caddy
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    environment:
      DOMAIN: ${DOMAIN}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
